#define OPEN_FILE_ERROR 1
#define CREATE_FILE_ERROR 2
#define GET_FILE_SIZE_ERROR 3
#define READ_DATA_ERROR 4
#define WRITE_DATA_ERROR 5
#define MEMORY_ALLOCATION_ERROR 6
#define COMMAND_LINE_ARGUMENTS_ERROR 7